# Site title will be used everywhere
title: Riverscapes Restoration Design Manual
description: > # this means to ignore newlines until "baseurl:"
  Online help and documentation site for the site

# Final root url of the site. No ending slash. No subdirectory
url: https://lowtechpbr.restoration.usu.edu
# If the site is in a subdirectory you should do it like this: "/subdirectory". Otherwise ""
baseurl: ""
# When serving locally what port should we use:
port: 4001

# Markdown style
markdown: kramdown
# Syntax highlighter.
highlighter: rouge

# Choosing "default" layout means we don't need a "layout:default" in all our 
# front matter
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Google Analytics
google_analytics: UA-146434571-3


# Files/Folders to exclude from publishing
exclude:
  - src
  - LICENSE
  - README.md
  - _config.yml
  - Gemfile*

remote_theme: Riverscapes/riverscapes-jekyll-theme
plugins:
  - jekyll-remote-theme 

# These are theme settings that will be used to turn features on and off
# They are not part of Jekyll, they are entirely custom.
settings:
  # Turn the automatically generated page contents on and off
  autoPageContents:
    active: true
    onHome: false
  # Options for the sidebar menu      
  sideMenu:
    homeItem: true
    startExpanded: false
  # Arbitrary multi-level topbar menu
  # IF you don't need this just comment out everything below
  # ----------------------------------
  topmenu:
    - title: "USU Watershed Sciences Department"
      url: https://qcnr.usu.edu/wats/
    - title: "LTPBR"
      url: http://lowtechpbr.restoration.usu.edu/
    - title: "Riverscapes Consortium"
      url: https://riverscapes.xyz
    - title: "Tools"
      url: https://riverscapes.xyz/Tools/
    - title: "Data"
      url: https://data.riverscapes.xyz
    - title: "Maps"
      url: https://maps.riverscapes.xyz

